<?php

namespace Ludows\Adminify\Commands;

use Illuminate\Console\Command;


class FlushCacheQuery extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'adminify:flush_cache_model';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'flush the cache generated by Adminify for model';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {

        $check = cache('cachable_keys_storage');

        if(!empty($check)) {
            cache()->forget('cachable_keys_storage');
            $this->info('cache model queries was flushed.');
        }

        return 0;
    }
}
